### ISSUE TITLE
New `mask` transformer

### ISSUE THREAD

**Issue by rabbitstack** [rabbitstack/fibratus#34]
The mask transformer should take care of masking sensitive data living in event parameters. Example config:

```
transformers:
     mask:
         char: *
         enabled: true
         kparams:
            - sip
            - dip
```
