### ISSUE TITLE
New `encrypt` transformer

### ISSUE THREAD

**Issue by rabbitstack** [rabbitstack/fibratus#35]
The `encrypt` transformer should encrypt event parameters with a specified crypto algorithm (e.g. AES). The original parameter value should get replaced with its respective hash string. Example config:

```
transformers:
    encrypt:
        algo: AES
        enabled: true
        kparams:
           - file_name
           - key_name
```
