### ISSUE TITLE
Function to drop event

### ISSUE THREAD

**Issue by asekhar** [rabbitstack/fibratus#53]
The configuration currently allows you to blacklist based on image names, etc. A function to drop/suppress events based on a combination of fields would be useful. For eg, I would like to process only file read events where the file has one of several extensions AND the image is not one of several. I dont believe the currrent configuration allows that. A function may be useful for this.

**Comment by rabbitstack** [comment]
Hi @asekhar 

Is this related to #49? I have to admit the issue name is a bit misleading, but the functionality would essentially allow defining various filters that are applied regardless of the filter expression you specify through CLI.

For example:

```yaml
kstream:
   filters:
       - kevt.name = 'ReadFile' and ps.name = 'cmd.exe' and file.extension in ('.txt', '.jpg', '.dll')
       - kevt.category = 'file' and file.extension not in ('.exe')
```

Would this be sufficient for your use case?
